version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7.6-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "TZ=@timezone@"
    networks:
      - local

  zipkin:
    image: openzipkin/zipkin:2.10.2
    container_name: zipkin
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    environment:
      - "TZ=@timezone@"
      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"
    networks:
      - local

networks:
  local: